name: Lint

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  trunk_check_runner:
    name: Trunk Check runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v1
        with:
          node-version: 20.12.0

      - name: Install packages
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Next Build (because it's more strict)
        run: pnpm run build
        env:
          NEXT_PUBLIC_SITE_URL: 'https://replay.io'
      - name: Check formatting
        run: pnpm run prettier:ci
