name: Playwright Tests
on: [pull_request]

jobs:
  wait-for-vercel:
    name: Wait for vercel
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: wait
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 120
    outputs:
      preview_url: ${{ steps.wait.outputs.url }}
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [wait-for-vercel]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: pnpm ci
      - name: Install Replay Chromium
        run: pnpx replayio install
      - name: Run Playwright tests
        run: pnpx playwright test --project replay-chromium
        env:
          BASE_URL: ${{ needs.wait-for-vercel.outputs.preview_url }}
          REPLAY_API_KEY: ${{ secrets.REPLAY_API_KEY }}
